// Destinations AI — Export Module
// Google Drive (Doc, Sheet), PDF, Email dispatch

import type { ExportOptions } from './types';

/** Export HTML content as a Google Doc via Drive API */
export async function exportToGoogleDoc(
  title: string,
  htmlContent: string,
  accessToken: string
): Promise<{ id: string; webViewLink: string }> {
  const metadata = {
    name: title,
    mimeType: 'application/vnd.google-apps.document',
  };

  const form = new FormData();
  form.append(
    'metadata',
    new Blob([JSON.stringify(metadata)], { type: 'application/json' })
  );
  form.append('file', new Blob([htmlContent], { type: 'text/html' }));

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${accessToken}` },
      body: form,
    }
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Google Doc export failed: ${err}`);
  }

  return res.json();
}

/** Export CSV data as a Google Sheet via Drive API */
export async function exportToGoogleSheet(
  title: string,
  csvData: string,
  accessToken: string
): Promise<{ id: string; webViewLink: string }> {
  const metadata = {
    name: title,
    mimeType: 'application/vnd.google-apps.spreadsheet',
  };

  const form = new FormData();
  form.append(
    'metadata',
    new Blob([JSON.stringify(metadata)], { type: 'application/json' })
  );
  form.append('file', new Blob([csvData], { type: 'text/csv' }));

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${accessToken}` },
      body: form,
    }
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Google Sheet export failed: ${err}`);
  }

  return res.json();
}

/** Build HTML report from export options (used for PDF and Doc export) */
export function buildReportHtml(options: ExportOptions): string {
  const data = options.data as Record<string, unknown>;
  const rows = Object.entries(data)
    .map(
      ([key, value]) =>
        `<tr><td style="padding:8px;border-bottom:1px solid #333;color:#a1a1aa">${key}</td><td style="padding:8px;border-bottom:1px solid #333;color:#e4e4e7;font-weight:600">${value}</td></tr>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${options.title}</title></head>
<body style="font-family:Inter,system-ui,sans-serif;background:#0A0A0F;color:#e4e4e7;padding:40px;max-width:800px;margin:0 auto">
  <div style="border-bottom:2px solid #D4A843;padding-bottom:16px;margin-bottom:24px">
    <h1 style="color:#D4A843;margin:0;font-size:24px">${options.title}</h1>
    <p style="color:#71717a;margin:4px 0 0;font-size:14px">Generated by Destinations AI — powered by A.I.M.S.</p>
  </div>
  <table style="width:100%;border-collapse:collapse">${rows}</table>
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #27273a;color:#52525b;font-size:12px">
    Destinations AI &copy; ${new Date().getFullYear()} A.I.M.S. — AI Managed Solutions
  </div>
</body>
</html>`;
}

/** Convert export data to CSV string */
export function buildCsv(data: Record<string, unknown>): string {
  const header = 'Field,Value';
  const rows = Object.entries(data)
    .map(([key, value]) => `"${key}","${String(value).replace(/"/g, '""')}"`)
    .join('\n');
  return `${header}\n${rows}`;
}

/** Dispatch export based on format */
export async function dispatchExport(
  options: ExportOptions,
  accessToken?: string
): Promise<{ success: boolean; url?: string; message?: string }> {
  switch (options.format) {
    case 'google_doc': {
      if (!accessToken) throw new Error('Google auth token required for Doc export');
      const html = buildReportHtml(options);
      const result = await exportToGoogleDoc(options.title, html, accessToken);
      return { success: true, url: result.webViewLink };
    }

    case 'google_sheet': {
      if (!accessToken) throw new Error('Google auth token required for Sheet export');
      const csv = buildCsv(options.data as Record<string, unknown>);
      const result = await exportToGoogleSheet(options.title, csv, accessToken);
      return { success: true, url: result.webViewLink };
    }

    case 'pdf': {
      // PDF generation returns the HTML — client renders via print or server-side puppeteer
      return { success: true, message: 'PDF ready for download' };
    }

    case 'email': {
      if (!options.recipientEmail) throw new Error('Recipient email required');
      // Email dispatch would go through A.I.M.S. gateway or SendGrid
      return { success: true, message: `Report queued for ${options.recipientEmail}` };
    }

    default:
      throw new Error(`Unsupported export format: ${options.format}`);
  }
}
